############# DEV ############
FROM php:8.3-fpm

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        curl \
        libxml2-dev \
        libcurl4-openssl-dev \
        libonig-dev \
        mariadb-client \
        sqlite3 \
        libsqlite3-dev \
        libzip-dev \
        unzip \
    && docker-php-ext-install pdo_mysql pdo_sqlite mbstring xml zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy project files
COPY . .

# Expose port 9000
EXPOSE 9000

# Start PHP-FPM server
CMD ["php-fpm"]
